### ISSUE TITLE
twrp .img for htc desire 620g dual sim

### ISSUE THREAD

**Issue by mohamedgewaly** [twrp-mtk/android_device_htc_htc_a31mg_dug#1]
hello 

i need  twrp .img   custom recovery file  for htc desire 620g dual sim

the file on twrp site for htc desire 620  and it's not working with me 

thanks for all

**Comment by hejsekvojtech** [comment]
That's because 620 has MSM8916 platform, the 620g on the other hand is mt6592.
This project is abandoned but you can grab the latest image available for your model here: https://androidfilehost.com/?fid=3700668719832237848
I cannot guarantee that it will boot since builds for HTC were blind builds

**Comment by mohamedgewaly** [comment]
thanks for reply
i tested this image but it's not working
thank you
